apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ordermapping
spec:
  selector:
    matchLabels:
      app: ordermapping
  replicas: 1 # comment - tells deployment to run 1 pods matching the template 
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: ordermapping
    spec:
      containers:
      - name: ordermapping
        image: mkadocker/ordermapping:BUILD_ID_PLACEHOLDER
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
          name: server
        - containerPort: 8089
          name: management
        env:
   
        